//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class afactivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public afactivo()
        {
            this.afactcomps = new HashSet<afactcomp>();
            this.afbceacts = new HashSet<afbceact>();
        }
    
        public int cia { get; set; }
        public int activo { get; set; }
        public string cod_alterno { get; set; }
        public string descrip { get; set; }
        public int tipo_activo { get; set; }
        public string tipo_activo2 { get; set; }
        public int grupo_activo { get; set; }
        public int ubic_activo { get; set; }
        public string marca { get; set; }
        public string modelo { get; set; }
        public string serie { get; set; }
        public int cantidad { get; set; }
        public int proveedor { get; set; }
        public string doc_pago { get; set; }
        public System.DateTime fecha_adq { get; set; }
        public decimal valor_adq { get; set; }
        public decimal adicion_rebaja { get; set; }
        public string observaciones { get; set; }
        public string texto1 { get; set; }
        public string texto2 { get; set; }
        public string texto3 { get; set; }
        public string texto4 { get; set; }
        public string texto5 { get; set; }
        public Nullable<int> cantidad1 { get; set; }
        public Nullable<int> cantidad2 { get; set; }
        public Nullable<int> cantidad3 { get; set; }
        public Nullable<int> cantidad4 { get; set; }
        public Nullable<int> cantidad5 { get; set; }
        public Nullable<decimal> valor1 { get; set; }
        public Nullable<decimal> valor2 { get; set; }
        public Nullable<decimal> valor3 { get; set; }
        public Nullable<decimal> valor4 { get; set; }
        public Nullable<decimal> valor5 { get; set; }
        public Nullable<System.DateTime> fecha1 { get; set; }
        public Nullable<System.DateTime> fecha2 { get; set; }
        public Nullable<System.DateTime> fecha3 { get; set; }
        public Nullable<System.DateTime> fecha4 { get; set; }
        public Nullable<System.DateTime> fecha5 { get; set; }
        public string reg_activo { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime hora_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afactcomp> afactcomps { get; set; }
        public virtual afgrupos afgrupos { get; set; }
        public virtual aftipoact aftipoact { get; set; }
        public virtual afubic afubic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<afbceact> afbceacts { get; set; }
    }
}
