//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cousuario
    {
        public string usuarioid { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int idioma { get; set; }
        public Nullable<int> ultima_cia { get; set; }
        public string status { get; set; }
        public string usuario { get; set; }
        public System.DateTime fecha_creacion { get; set; }
        public System.DateTime hora_creacion { get; set; }
        public Nullable<System.DateTime> fecha_modificacion { get; set; }
    }
}
