//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GOFFICE_DATAEntities : DbContext
    {
        public GOFFICE_DATAEntities()
            : base("name=GOFFICE_DATAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afactcomp> afactcomps { get; set; }
        public virtual DbSet<afactivo> afactivos { get; set; }
        public virtual DbSet<afbceact> afbceacts { get; set; }
        public virtual DbSet<afgrupos> afgrupos { get; set; }
        public virtual DbSet<aftipoact> aftipoacts { get; set; }
        public virtual DbSet<afubic> afubics { get; set; }
        public virtual DbSet<cousuario> cousuarios { get; set; }
    }
}
